spring:
  datasource:
    url: jdbc:h2:mem:testdb
    schema: schema.sql
    data: data.sql
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

logging:
  level:
    root: ERROR
