DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID IDENTITY NOT NULL PRIMARY KEY, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID IDENTITY NOT NULL PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID IDENTITY NOT NULL PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);
