version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  library:
    container_name: library
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - mongo
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb_data: