version: '3'
services:
  library:
    container_name: library
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:8080
    environment:
      - MONGO_DB=library
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: