spring:
  data:
    mongodb:
      database: library
      host: localhost
      port: 27017

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.dlyubanevich.mongock.changelog

logging:
  file:
    name: "library.log"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  health:
    defaults:
      enabled: true

actuator:
  health:
    uri: "http://localhost:8080/api/library"
